Repository leroy-merlin-br/metamorphosis, pull requests merged in 2018-08, with the labels that each got.

#5 Adds TravisCi integration and Coveralls
  .coveralls.yml
  .travis.yml
  Makefile
  composer.json
  phpunit.xml
Labels: code-review

#6 Adds code coverage
  phpunit.xml.dist
Labels: enhancement

#7 Middlewares support
  config/kafka.php
  src/Config.php
  src/Consumer.php
  src/Contracts/ConsumerTopicHandler.php
  src/Contracts/Middleware.php
  src/Contracts/MiddlewareHandler.php
  src/Message.php
  src/Middlewares/AbstractMiddlewareHandler.php
  src/Middlewares/AvroDecode.php
  src/Middlewares/Consumer.php
  src/Middlewares/Dispatcher.php
  src/Middlewares/Iterator.php
  src/Middlewares/Log.php
  tests/ConfigTest.php
  tests/Dummies/ConsumerHandlerDummy.php
  tests/MessageTest.php
  tests/Middlewares/IteratorTest.php
  tests/Middlewares/LogTest.php
Labels: work-in-progress

#2 Create command for running consumers
  composer.json
  config/kafka.php
  phpunit.xml
  readme.md
  src/Authentication/Authentication.php
  src/Authentication/Factory.php
  src/Authentication/NoAuthentication.php
  src/Authentication/SSLAuthentication.php
  src/Broker.php
  src/Config.php
  src/Connector.php
  src/Console/Command.php
  src/Console/ConsumerMakeCommand.php
  src/Console/stubs/consumer.stub
  src/Consumer.php
  src/Exceptions/AuthenticationException.php
  src/Message.php
  src/MetamorphosisServiceProvider.php
  src/Middlewares/AvroDecode.php
  src/Middlewares/Handler/AbstractMiddlewareHandler.php
  src/Middlewares/Handler/Consumer.php
  src/Middlewares/Handler/Dispatcher.php
  src/Middlewares/Handler/Iterator.php
  src/Middlewares/Handler/MiddlewareHandler.php
  src/Middlewares/Log.php
  src/Middlewares/Middleware.php
  src/TopicHandler/Consumer/AbstractHandler.php
  src/TopicHandler/Consumer/Handler.php
  tests/Authentication/FactoryTest.php
  tests/Authentication/SSLAuthenticationTest.php
  tests/BrokerTest.php
  tests/ConfigTest.php
  tests/ConnectorTest.php
  tests/Console/CommandTest.php
  tests/Dummies/ConsumerHandlerDummy.php
  tests/LaravelTestCase.php
  tests/MessageTest.php
  tests/Middlewares/Handler/ConsumerTest.php
  tests/Middlewares/Handler/DispatcherTest.php
  tests/Middlewares/Handler/IteratorTest.php
  tests/Middlewares/LogTest.php
  tests/test-helpers.php
Labels: work-in-progress

#11 Implement whitelist for certain message errors
  src/Console/stubs/consumer.stub
  src/Consumer.php
  src/Exceptions/ResponseErrorException.php
  src/Exceptions/ResponseWarningException.php
  src/Message.php
  src/TopicHandler/Consumer/AbstractHandler.php
  src/TopicHandler/Consumer/Handler.php
  tests/MessageTest.php
Labels: code-review

#13 Add test for ConsumerMakeCommand
  tests/Console/ConsumerMakeCommandTest.php
Labels: enhancement

#16 Update stubs/consumer
  src/Console/stubs/consumer.stub
Labels: bug

#17 allow to set connection broker as array
  config/kafka.php
  src/Broker.php
  src/Config.php
  src/Connector.php
  tests/BrokerTest.php
  tests/ConfigTest.php
  tests/Console/CommandTest.php
Labels: code-review

#15 Change php72-fpm container to php72-cli
  docker-compose.yml
  docker/Dockerfile
Labels: code-review

#18 Refactor Consumer
  src/Broker.php
  src/Config.php
  src/Connector.php
  src/Console/Command.php
  src/Consumer.php
  tests/BrokerTest.php
  tests/ConnectorTest.php
  tests/ConsumerTest.php
  tests/Dummies/MiddlewareDummy.php
Labels: code-review, enhancement

#20 Change Handler::handle signature to return void
  src/Console/stubs/consumer.stub
  src/TopicHandler/Consumer/Handler.php
  tests/Dummies/ConsumerHandlerDummy.php
Labels: code-review

#21 Handle no middleware configuration
  src/Config.php
  tests/ConfigTest.php
Labels: code-review

#23 Record tweaks
  src/Console/stubs/consumer.stub
  src/Console/stubs/middleware.stub
  src/Consumer.php
  src/Middlewares/AvroDecode.php
  src/Middlewares/Handler/AbstractMiddlewareHandler.php
  src/Middlewares/Handler/Consumer.php
  src/Middlewares/Handler/Dispatcher.php
  src/Middlewares/Handler/Iterator.php
  src/Middlewares/Handler/MiddlewareHandler.php
  src/Middlewares/Log.php
  src/Middlewares/Middleware.php
  src/Record.php
  src/TopicHandler/Consumer/Handler.php
  tests/Dummies/ConsumerHandlerDummy.php
  tests/Dummies/MiddlewareDummy.php
  tests/MessageTest.php
  tests/Middlewares/AvroDecodeTest.php
  tests/Middlewares/Handler/ConsumerTest.php
  tests/Middlewares/Handler/DispatcherTest.php
  tests/Middlewares/Handler/IteratorTest.php
  tests/Middlewares/LogTest.php
Labels: code-review, enhancement

#24 Add docblocks to Record
  src/Record.php
  tests/RecordTest.php
Labels: code-review, enhancement

#14 Improve Readme
  config/kafka.php
  docs/CONTRIBUTING.md
  docs/advanced.md
  docs/logo.jpg
  readme.md
  src/Console/ConsumerMakeCommand.php
Labels: code-review, enhancement

#27 Big Tweaks
  config/kafka.php
  docs/advanced.md
  readme.md
  src/Config.php
  src/Connectors/Consumer/ConnectorFactory.php
  src/Connectors/Consumer/ConnectorInterface.php
  src/Connectors/Consumer/HighLevel.php
  src/Connectors/Consumer/LowLevel.php
  src/Console/Command.php
  src/Console/stubs/middleware.stub
  src/Consumers/ConsumerInterface.php
  src/Consumers/HighLevel.php
  src/Consumers/LowLevel.php
  src/Record.php
  src/Runner.php
  tests/ConfigTest.php
  tests/ConnectorTest.php
  tests/Connectors/Consumer/ConnectorFactoryTest.php
  tests/Connectors/Consumer/HighLevelTest.php
  tests/Connectors/Consumer/LowLevelTest.php
  tests/Console/CommandTest.php
  tests/Consumers/HighLevelTest.php
  tests/Consumers/LowLevelTest.php
  tests/RunnerTest.php
Labels: enhancement, work-in-progress

#30 Create LICENSE
  LICENSE
Labels: enhancement
