Repository leroy-merlin-br/metamorphosis, pull requests merged in 2018-10, with the labels that each got.

#39 Remove undefined environment variable from config
  config/kafka.php
Labels: bug, code-review

#43 Remove warning about beta-stage
  readme.md
Labels: code-review

#44 Make broker connection overridable through option on command
  docs/advanced.md
  readme.md
  src/Config/AbstractConfig.php
  src/Config/Consumer.php
  src/Console/ConsumerCommand.php
  tests/Config/ConsumerTest.php
  tests/Console/ConsumerCommandTest.php
Labels: code-review, enhancement
