Repository leroy-merlin-br/metamorphosis, pull requests merged in 2019-12, with the labels that each got.

#58 Improve docker
  .gitignore
  .travis.yml
  Makefile
  docker-compose.yml
  docker/Dockerfile
  docker/php-ini-overrides.ini
  phpunit.xml.dist
Labels: code-review

#59 DRY & Dockblock
  src/AbstractConfig.php
  src/Connectors/Consumer/Config.php
  src/Connectors/Consumer/ConnectorFactory.php
  src/Connectors/Producer/Config.php
Labels: enhancement

#60 Create Application Manager instead of use configs
  config/kafka.php
  src/Authentication/Factory.php
  src/Authentication/SSLAuthentication.php
  src/AvroConsumerRunner.php
  src/Connectors/AbstractConfig.php
  src/Connectors/Consumer/Config.php
  src/Connectors/Consumer/ConnectorFactory.php
  src/Connectors/Consumer/HighLevel.php
  src/Connectors/Consumer/LowLevel.php
  src/Connectors/Producer/Config.php
  src/Connectors/Producer/Connector.php
  src/Console/ConsumerCommand.php
  src/ConsumerRunner.php
  src/Consumers/HighLevel.php
  src/Consumers/LowLevel.php
  src/Consumers/Runner.php
  src/Facades/Manager.php
  src/Manager.php
  src/MetamorphosisServiceProvider.php
  src/Middlewares/AvroSchemaDecoder.php
  src/Middlewares/Handler/Iterator.php
  src/Producer.php
  src/RunnerFactory.php
  tests/Authentication/FactoryTest.php
  tests/Authentication/SSLAuthenticationTest.php
  tests/Connectors/Consumer/ConfigTest.php
  tests/Connectors/Consumer/HighLevelTest.php
  tests/Connectors/Consumer/LowLevelTest.php
  tests/Connectors/Producer/ConnectorTest.php
  tests/Console/ConsumerCommandTest.php
  tests/Consumers/HighLevelTest.php
  tests/Consumers/LowLevelTest.php
  tests/Consumers/RunnerTest.php
  tests/ManagerTest.php
Labels: enhancement

#61 Allow request options when get avro schema
  composer.json
  composer.lock
  config/kafka.php
  src/Avro/CachedSchemaRegistryClient.php
  src/Avro/Client.php
  src/Connectors/Consumer/Config.php
  src/Middlewares/AvroSchemaDecoder.php
  tests/Avro/CachedSchemaRegistryClientTest.php
  tests/Connectors/Consumer/ConfigTest.php
Labels: code-review, enhancement

#62 Use IOC On Avro Client
  src/Avro/CachedSchemaRegistryClient.php
  src/Avro/Client.php
  src/MetamorphosisServiceProvider.php
  src/Middlewares/AvroSchemaDecoder.php
  tests/Avro/CachedSchemaRegistryClientTest.php
Labels: enhancement

#64 Update Producer
  src/Connectors/Producer/Connector.php
Labels: enhancement
