Repository leroy-merlin-br/metamorphosis, pull requests merged in 2020-01, with the labels that each got.

#65 Improve Producer
  config/kafka.php
  src/Connectors/Producer/Config.php
  src/Connectors/Producer/Connector.php
  src/Connectors/Producer/Queue.php
  src/MetamorphosisServiceProvider.php
  src/Middlewares/Handler/Producer.php
  src/Producer.php
  src/TopicHandler/Producer/AbstractHandler.php
  src/TopicHandler/Producer/HandlerInterface.php
  tests/Connectors/Producer/ConfigTest.php
  tests/Connectors/Producer/ConnectorTest.php
  tests/Connectors/Producer/QueueTest.php
  tests/Middlewares/Handler/ProducerTest.php
  tests/ProducerTest.php
Labels: code-review, enhancement

#68 Portuguese docblock
  docs/advanced.md
  docs/advanced.pt.md
  docs/quick-usage.pt.md
  readme.md
  readme.pt.md
  src/Console/stubs/consumer.stub
Labels: code-review, enhancement

#74 Add partition config to producer
  config/kafka.php
  src/Connectors/Producer/Config.php
  src/TopicHandler/Producer/AbstractHandler.php
  tests/Unit/Connectors/Producer/ConfigTest.php
  tests/Unit/TopicHandler/Producer/AbstractHandlerTest.php
Labels: enhancement

#75 Update Producer to use poll instead Flush
  src/Middlewares/Handler/Producer.php
  tests/Unit/Middlewares/Handler/ProducerTest.php
Labels: enhancement

#76 Fix middlewares config
  src/Manager.php
  tests/Unit/ManagerTest.php
Labels: bug

#77 Fix default partition config
  src/Middlewares/Handler/Producer.php
  src/TopicHandler/Producer/AbstractHandler.php
  tests/Unit/Middlewares/Handler/ProducerTest.php
  tests/Unit/ProducerTest.php
  tests/Unit/TopicHandler/Producer/AbstractHandlerTest.php
Labels: bug, code-review

#78 Allow handle consume commit
  config/kafka.php
  src/Authentication/Factory.php
  src/Authentication/SSLAuthentication.php
  src/ConfigManager.php
  src/Connectors/AbstractConfig.php
  src/Connectors/Consumer/Config.php
  src/Connectors/Consumer/ConnectorFactory.php
  src/Connectors/Consumer/ConnectorInterface.php
  src/Connectors/Consumer/Factory.php
  src/Connectors/Consumer/HighLevel.php
  src/Connectors/Consumer/LowLevel.php
  src/Connectors/Consumer/Manager.php
  src/Connectors/Producer/Config.php
  src/Connectors/Producer/Connector.php
  src/Console/ConsumerCommand.php
  src/Consumers/HighLevel.php
  src/Consumers/LowLevel.php
  src/Consumers/Runner.php
  src/Facades/ConfigManager.php
  src/MetamorphosisServiceProvider.php
  src/Middlewares/AvroSchemaDecoder.php
  src/Middlewares/Handler/Producer.php
  src/Producer.php
  src/Producer/Poll.php
  tests/Unit/Authentication/FactoryTest.php
  tests/Unit/Authentication/SSLAuthenticationTest.php
  tests/Unit/Connectors/Consumer/ConfigTest.php
  tests/Unit/Connectors/Consumer/FactoryTest.php
  tests/Unit/Connectors/Consumer/HighLevelTest.php
  tests/Unit/Connectors/Consumer/LowLevelTest.php
  tests/Unit/Connectors/Consumer/ManagerTest.php
  tests/Unit/Connectors/Producer/ConfigTest.php
  tests/Unit/Console/ConsumerCommandTest.php
  tests/Unit/Consumers/HighLevelTest.php
  tests/Unit/Consumers/LowLevelTest.php
  tests/Unit/Consumers/RunnerTest.php
  tests/Unit/ManagerTest.php
  tests/Unit/Middlewares/Handler/ProducerTest.php
  tests/Unit/Producer/PollTest.php
  tests/Unit/ProducerTest.php
Labels: enhancement
